### ISSUE TITLE
测试时遇到ValueError: not enough values to unpack (expected 8, got 7)问题

### ISSUE THREAD

**Issue by zy6588** [SAIC-Vision/WS-3D-Lane#3]
Traceback (most recent call last):
  File "test.py", line 145, in <module>
    main()
  File "test.py", line 142, in main
    trainer.evaluation()
  File "test.py", line 88, in evaluation
    img, _, gt, idx, gt_hcam, gt_pitch, imgname, _ = batch
ValueError: not enough values to unpack (expected 8, got 7)

**Comment by zy6588** [comment]
解决办法是

**Comment by zy6588** [comment]
解决方法是将：
img, _, gt, idx, gt_hcam, gt_pitch, imgname, _ = batch
修改为
img, gt, idx, gt_hcam, gt_pitch, imgname, _ = batch
